spring:
  data:
    mongodb:
      uri: mongodb+srv://cardmates:cardmates!!@wisecard.fqjvpgx.mongodb.net/wisecard?retryWrites=true&w=majority&appName=wisecard

grpc:
  server:
    port: 50052
server:
  port: 8081

kakao:
  rest-api-key: 6e04cfc94461a18e2b77b3a859e2ef0f
